global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-service:9104']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-service:9113']
