apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.26.0
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
        volumeMounts:
          - mountPath: /etc/prometheus
            name: prometheus-config
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
